spring.application.name=bank-api
server.port=${PORT:8080}
app.db.url=jdbc:sqlite:${DB_FILE:data/db.db}

spring.jackson.serialization.write-dates-as-timestamps=false

springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/openapi.json
